<?php

if( function_exists('acf_add_options_page') ) {
  
  acf_add_options_page();
  
}



add_filter('acf/location/rule_types', 'acf_location_rules_types');

function acf_location_rules_types( $choices ) {
  
    $choices['Taxonomies']['taxonomy'] = 'taxonomy';

    return $choices;
    
}

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_587634d6db551',
  'title' => 'Colonne',
  'fields' => array (
    array (
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'default_value' => '',
      'delay' => 0,
      'key' => 'field_587634e3d237e',
      'label' => 'Contenu de la Colonne à gauche',
      'name' => 'sidebar_content',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-sidebar.php',
      ),
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-soumettre.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_587dd3fac6c22',
  'title' => 'Détails sur la Thématique / Boite à outils',
  'fields' => array (
    array (
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'default_value' => '',
      'delay' => 0,
      'key' => 'field_589458cbca39a',
      'label' => 'Texte de présentation',
      'name' => 'presentation',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'return_format' => 'id',
      'preview_size' => 'medium',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
      'key' => 'field_587dd44a8c61e',
      'label' => 'Image principale',
      'name' => 'image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'taxonomy' => 'post_tag',
      'field_type' => 'checkbox',
      'multiple' => 0,
      'allow_null' => 1,
      'return_format' => 'object',
      'add_term' => 0,
      'load_terms' => 0,
      'save_terms' => 0,
      'key' => 'field_5894503910b39',
      'label' => 'Mots clefs liés',
      'name' => 'tags_linked',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'taxonomy' => 'category',
      'field_type' => 'checkbox',
      'multiple' => 0,
      'allow_null' => 1,
      'return_format' => 'object',
      'add_term' => 0,
      'load_terms' => 0,
      'save_terms' => 0,
      'key' => 'field_5894506910b3a',
      'label' => 'Thématiques liées',
      'name' => 'themes_linked',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'taxonomy' => 'boiteoutils',
      'field_type' => 'checkbox',
      'multiple' => 0,
      'allow_null' => 1,
      'return_format' => 'object',
      'add_term' => 0,
      'load_terms' => 0,
      'save_terms' => 0,
      'key' => 'field_5894508510b3b',
      'label' => 'Boites à outils liées',
      'name' => 'boites_linked',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'taxonomy',
        'operator' => '==',
        'value' => 'category',
      ),
    ),
    array (
      array (
        'param' => 'taxonomy',
        'operator' => '==',
        'value' => 'boiteoutils',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_587f88e9471a7',
  'title' => 'Diaporama',
  'fields' => array (
    array (
      'library' => 'all',
      'min' => '',
      'max' => '',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
      'insert' => 'append',
      'key' => 'field_587f892f45e18',
      'label' => 'Images du Diaporama',
      'name' => 'images',
      'type' => 'gallery',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'preview_size' => 'thumbnail',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'contenu',
      ),
    ),
    array (
      array (
        'param' => 'post_taxonomy',
        'operator' => '==',
        'value' => 'format:diaporama',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_5877a93fe8d8d',
  'title' => 'Éléments de la Grille d\'accueil',
  'fields' => array (
    array (
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'key' => 'field_5877a9597d1ca',
      'label' => 'Titre de la Grille',
      'name' => 'grille_titre',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
      'key' => 'field_5877a9677d1cb',
      'label' => 'Page au premier emplacement',
      'name' => 'grille_page_1',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
      'key' => 'field_5877a9877d1cc',
      'label' => 'Page au deuxième emplacement',
      'name' => 'grille_page_2',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'post_type' => array (
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
      'key' => 'field_5877a99c7d1cd',
      'label' => 'Page au troisième emplacement',
      'name' => 'grille_page_3',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'post_type' => array (
        0 => 'post',
        1 => 'contenu',
      ),
      'taxonomy' => array (
        0 => 'format:video',
        1 => 'format:audio',
        2 => 'format:diaporama',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
      'key' => 'field_5877a9ae7d1ce',
      'label' => 'Média',
      'name' => 'grille_media',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-home.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_58779e8e23016',
  'title' => 'Option du Zoom',
  'fields' => array (
    array (
      'return_format' => 'array',
      'preview_size' => 'medium',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
      'key' => 'field_5877a1490e1d1',
      'label' => 'Image du Zoom',
      'name' => 'zoom_image',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'key' => 'field_58779ea16b252',
      'label' => 'Titre du Zoom',
      'name' => 'zoom_titre',
      'type' => 'text',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'taxonomy' => 'category',
      'field_type' => 'select',
      'multiple' => 0,
      'allow_null' => 0,
      'return_format' => 'object',
      'add_term' => 1,
      'load_terms' => 0,
      'save_terms' => 0,
      'key' => 'field_58779fc7a5854',
      'label' => 'Thématique concernée',
      'name' => 'zoom_thematique',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'default_value' => '',
      'delay' => 0,
      'key' => 'field_58779fa36b254',
      'label' => 'Chapo du Zoom',
      'name' => 'zoom_texte',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 1,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'post_type' => array (
        0 => 'structure',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
      'key' => 'field_5877a0018d091',
      'label' => 'Association liée',
      'name' => 'zoom_association',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'default_value' => '',
      'new_lines' => 'wpautop',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
      'key' => 'field_589310b760682',
      'label' => 'Texte pour association liée',
      'name' => 'zoom_association_text',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'post_type' => array (
        0 => 'pays',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'return_format' => 'object',
      'ui' => 1,
      'key' => 'field_5877a0288d092',
      'label' => 'Pays lié',
      'name' => 'zoom_pays',
      'type' => 'post_object',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
      'key' => 'field_58a4766b91e42',
      'label' => 'Image pour le pays lié',
      'name' => 'zoom_pays_img',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '==',
        'value' => 'page-home.php',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => array (
    0 => 'the_content',
    1 => 'excerpt',
    2 => 'discussion',
    3 => 'comments',
    4 => 'format',
    5 => 'featured_image',
    6 => 'categories',
    7 => 'tags',
    8 => 'send-trackbacks',
  ),
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_58807c934e113',
  'title' => 'Options du footer',
  'fields' => array (
    array (
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'default_value' => '',
      'delay' => 0,
      'key' => 'field_58807ca0297bb',
      'label' => 'Texte de présentation',
      'name' => 'elsa_text',
      'type' => 'wysiwyg',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'library' => 'all',
      'min' => '',
      'max' => '',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
      'insert' => 'append',
      'key' => 'field_589311c8bc6c4',
      'label' => 'Logos Membres',
      'name' => 'logos_membres',
      'type' => 'gallery',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'preview_size' => 'thumbnail',
    ),
    array (
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'key' => 'field_589311dbbc6c5',
      'label' => '"Titre" sous logos membres',
      'name' => 'logos_membres_title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_587636518a278',
  'title' => 'Options Menus',
  'fields' => array (
    array (
      'placement' => 'top',
      'endpoint' => 0,
      'key' => 'field_587f3e1461a9d',
      'label' => 'Dropdown Thématiques',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'default_value' => 'Thématique à la Une',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'key' => 'field_587f334410477',
      'label' => 'Titre thématique à la Une',
      'name' => 'dd-theme-title-1',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'taxonomy' => 'category',
      'field_type' => 'checkbox',
      'multiple' => 0,
      'allow_null' => 0,
      'return_format' => 'id',
      'add_term' => 1,
      'load_terms' => 0,
      'save_terms' => 0,
      'key' => 'field_587f339d10478',
      'label' => 'Thématique à la une n°1',
      'name' => 'dd-theme-1',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'default_value' => '',
      'new_lines' => 'wpautop',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
      'key' => 'field_587f33e01047a',
      'label' => 'Thématique à la une n°1 - Texte',
      'name' => 'dd-theme-1-text',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'taxonomy' => 'category',
      'field_type' => 'checkbox',
      'multiple' => 0,
      'allow_null' => 0,
      'return_format' => 'id',
      'add_term' => 1,
      'load_terms' => 0,
      'save_terms' => 0,
      'key' => 'field_587f33cc10479',
      'label' => 'Thématique à la une n°2',
      'name' => 'dd-theme-2',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'default_value' => '',
      'new_lines' => 'wpautop',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
      'key' => 'field_587f340f1047b',
      'label' => 'Thématique à la une n°1 - Texte',
      'name' => 'dd-theme-2-text',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'default_value' => 'Toutes les thématiques',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'key' => 'field_587f342df9e96',
      'label' => 'Titre toutes les thématiques',
      'name' => 'dd-theme-title-2',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'placement' => 'top',
      'endpoint' => 0,
      'key' => 'field_587f3e0061a9c',
      'label' => 'Dropdown Boite à outils',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'default_value' => 'Toutes les Boites à outils',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'key' => 'field_587f3e2f61a9e',
      'label' => 'Titre du dropdown',
      'name' => 'dd-boite-title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
      'key' => 'field_587f3e4a61a9f',
      'label' => 'Image du dropdown',
      'name' => 'dd-boite-img',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'default_value' => '',
      'new_lines' => 'wpautop',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
      'key' => 'field_587f3eca61aa0',
      'label' => 'Texte d\'intro du dropdown',
      'name' => 'dd-boite-text',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'placement' => 'top',
      'endpoint' => 0,
      'key' => 'field_587f3f77c7862',
      'label' => 'Dropdown Pays',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'default_value' => 'Tous les pays',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'key' => 'field_587f3f86c7863',
      'label' => 'Titre du dropdown',
      'name' => 'dd-pays-title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'return_format' => 'url',
      'preview_size' => 'thumbnail',
      'library' => 'all',
      'min_width' => '',
      'min_height' => '',
      'min_size' => '',
      'max_width' => '',
      'max_height' => '',
      'max_size' => '',
      'mime_types' => '',
      'key' => 'field_587f3f95c7864',
      'label' => 'Visuel du dropdown',
      'name' => 'dd-pays-img',
      'type' => 'image',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'placement' => 'top',
      'endpoint' => 0,
      'key' => 'field_587f4132fa13b',
      'label' => 'Dropdown Associations',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'default_value' => 'Toutes les associations',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'key' => 'field_587f413dfa13c',
      'label' => 'Titre du dropdown',
      'name' => 'dd-assos-title',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'default_value' => '',
      'new_lines' => 'wpautop',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
      'key' => 'field_587f414afa13d',
      'label' => 'Texte du dropdown',
      'name' => 'dd-assos-text',
      'type' => 'textarea',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'post_type' => array (
        0 => 'page',
      ),
      'taxonomy' => array (
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'allow_archives' => 1,
      'key' => 'field_587f416cfa13e',
      'label' => 'Page contenant l\'annuaire',
      'name' => 'dd-assos-url',
      'type' => 'page_link',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_587dfaa13a22c',
  'title' => 'Rebonds par défaut',
  'fields' => array (
    array (
      'post_type' => array (
        0 => 'post',
        1 => 'page',
        2 => 'pays',
        3 => 'structure',
        4 => 'contenu',
      ),
      'taxonomy' => array (
      ),
      'min' => '',
      'max' => '',
      'filters' => array (
        0 => 'search',
        1 => 'post_type',
        2 => 'taxonomy',
      ),
      'elements' => array (
        0 => 'featured_image',
      ),
      'return_format' => 'object',
      'key' => 'field_587dfaba91e62',
      'label' => 'Liste des blocs à faire apparaitre par défaut',
      'name' => 'rebonds_default',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => 'Les rebonds sont les éléments qui apparaissent dans certaines pages sous le titre "Autres infos utiles"',
));

acf_add_local_field_group(array (
  'key' => 'group_588718cb24853',
  'title' => 'Rebonds par page',
  'fields' => array (
    array (
      'post_type' => array (
        0 => 'post',
        1 => 'page',
        2 => 'structure',
        3 => 'pays',
        4 => 'contenu',
      ),
      'taxonomy' => array (
      ),
      'min' => '',
      'max' => '',
      'filters' => array (
        0 => 'search',
        1 => 'post_type',
        2 => 'taxonomy',
      ),
      'elements' => '',
      'return_format' => 'object',
      'key' => 'field_588718f7f9ea0',
      'label' => 'Listes des pages à lier',
      'name' => 'listes_des_pages_à_lier',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'post',
      ),
    ),
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'structure',
      ),
    ),
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'pays',
      ),
    ),
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'contenu',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => 'Lister ici les pages à afficher dans le module \'Autres infos utiles\'. Des pages par défaut ont été défini pour tous. Les pages choisies ici s\'ajouteront à ces pages par "défaut".',
));

acf_add_local_field_group(array (
  'key' => 'group_5890bd7d56dff',
  'title' => 'Réseaux sociaux',
  'fields' => array (
    array (
      'default_value' => '',
      'placeholder' => '',
      'key' => 'field_5890bd86292c1',
      'label' => 'Page facebook',
      'name' => 'url_facebook',
      'type' => 'url',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'default_value' => '',
      'placeholder' => '',
      'key' => 'field_5890bd95292c2',
      'label' => 'Page Twitter',
      'name' => 'url_twitter',
      'type' => 'url',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'side',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_58778cfe5fe6b',
  'title' => 'Soumettre un ressource',
  'fields' => array (
    array (
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'key' => 'field_58778d1b4f59d',
      'label' => 'Titre',
      'name' => 'tsm_titre',
      'type' => 'text',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'taxonomy' => 'category',
      'field_type' => 'multi_select',
      'multiple' => 0,
      'allow_null' => 0,
      'return_format' => 'id',
      'add_term' => 1,
      'load_terms' => 1,
      'save_terms' => 1,
      'key' => 'field_58778d3d4f59e',
      'label' => 'Thématique',
      'name' => 'tsm_thematique',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
    array (
      'return_format' => 'array',
      'library' => 'uploadedTo',
      'min_size' => '',
      'max_size' => 5,
      'mime_types' => 'pdf, png, jpg',
      'key' => 'field_58778d7a4f59f',
      'label' => 'Fichier',
      'name' => 'tsm_file',
      'type' => 'file',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

acf_add_local_field_group(array (
  'key' => 'group_587dededac708',
  'title' => 'Recommandation',
  'fields' => array (
    array (
      'default_value' => 0,
      'message' => '',
      'ui' => 0,
      'ui_on_text' => '',
      'ui_off_text' => '',
      'key' => 'field_587dee05bd06b',
      'label' => 'Cette ressource est recommandée par le comité de lecture',
      'name' => 'recommandation',
      'type' => 'true_false',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'post',
      ),
    ),
  ),
  'menu_order' => 2,
  'position' => 'side',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;